name: Docker Run on Merge PR
on:
  push:
    branches:
      - main
jobs:
  docker-run:
    runs-on: self-hosted
    steps:
      - name: Docker run
        run: docker run -d --name portfolio-fe -p 3334:80 --rm portfolio
