name: Build And Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build -t portfolio .

      - name: Docker stop old container
        run: docker container stop portfolio-fe || true

      - name: Docker run
        run: docker run -d --name portfolio-fe -p 3334:80 --rm portfolio
